name: C/C++ CI

on: [push]

jobs:

  test:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1

    - name: Set up cmake
      run: sudo apt-get update && 
           sudo apt-get install -y cmake 

    - name: Change an active directory
      run: cd tests

    - name: CMake
      run: cmake .

    - name: make
      run: make

    - name: Run all the tests
      run: ./tests