name: C/C++ CI

on: [push]

jobs:

  test:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1

    - name: Set up cmake
      run: sudo apt-get update && 
           sudo apt-get install -y cmake 

    - name: Create a bin folder
      run: mkdir tests/bin


    - name: CMake
      working-directory: ./tests/bin
      run: cmake ..

    - name: make
      run: make

    - name: Run all the tests
      run: ./tests