name: C/C++ CI

on: [push]

jobs:

  test:

    runs-on: ubuntu-latest
    
    steps:
    
    - name: Check out code
      uses: actions/checkout@v2

    - name: action-gtest
      uses: CyberZHG/github-action-gtest@0.0.1
      with:
        args: "-d ./Tests -e tests"

