name: C/C++ CI

on: [push]

jobs:

  test:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1

    - name: Set up cmake
      run: sudo apt-get update && 
           sudo apt-get install -y cmake 

    - name: ls
      run: ls

    - name: Git log
      run: git log